# Generated by Django 5.2.3 on 2025-06-27 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('birthdate', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=12)),
                ('parent_name', models.CharField(max_length=30)),
                ('parent_email', models.EmailField(max_length=100)),
                ('parent_phone_number', models.CharField(max_length=12)),
                ('other_phone_number', models.CharField(max_length=15)),
                ('school_details', models.TextField()),
                ('current_grade', models.CharField(max_length=10)),
                ('subjects_of_interest', models.CharField(max_length=80)),
                ('preferred_tutor_mode', models.CharField(max_length=16)),
                ('language_preferences', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
