# Generated by Django 5.1.6 on 2025-03-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='subject',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='yoe',
            field=models.CharField(default='0yrs', max_length=50),
            preserve_default=False,
        ),
    ]
