# Generated by Django 5.2.3 on 2025-06-27 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('date_of_birth', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('profile_picture', models.ImageField(upload_to='tutor_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TutorPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching_mode', models.CharField(max_length=20)),
                ('age_group', models.CharField(max_length=30)),
                ('travel_preference', models.CharField(max_length=10)),
                ('fee_range', models.CharField(max_length=10)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutors.tutorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TutorIntroduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('tagline', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='tutor-intro/')),
                ('resume', models.FileField(upload_to='tutors-resume/')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutors.tutorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TutorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_qualification', models.CharField(max_length=100)),
                ('subjects_taught', models.CharField(max_length=100)),
                ('teaching_experience', models.IntegerField(max_length=50)),
                ('language_spoken', models.CharField(max_length=50)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutors.tutorprofile')),
            ],
        ),
    ]
