# Generated by Django 5.2.3 on 2025-06-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutordetails',
            name='teaching_experience',
            field=models.CharField(max_length=50),
        ),
    ]
